version: '2'
services:
  db:
    image: mongo
    command: mongod --smallfiles
    ports:
      - "27017"
      - "28017"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./script/start
    volumes:
      - .:/workspace
      - bundler:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db
      - webpacker
  webpacker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./script/webpacker
    volumes:
      - .:/workspace
      - bundler:/usr/local/bundle
    ports:
      - "3035:3035"
volumes:
  bundler: {}
