db:
  image: mongo
  command: mongod --smallfiles
  ports:
    - "27017"
    - "28017"
web:
  build: .
  dockerfile: Dockerfile.dev
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/workspace
  volumes_from:
    - bundler
  ports:
    - "3000:3000"
  links:
    - db
bundler:
  image: busybox
  volumes:
    - /bundler
