version: '3'
services:
  db:
    image: mongo:4.0
    command: mongod --smallfiles --bind_ip_all
  _build:
    command: ['echo', 'build completed']
    build:
      context: .
      dockerfile: Dockerfile.dev
    <<: &image
      image: CHANGEME
  app:
    <<: *image
    command: ./script/start
    volumes:
      - .:/workspace
      - bundler:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - _build
  esbuild:
    <<: *image
    command: ./script/esbuild
    tty: true
    volumes:
      - .:/workspace
      - bundler:/usr/local/bundle
    depends_on:
      - _build
volumes:
  bundler: {}
