version: '3'
services:
  db:
    image: mongo:3.6
    command: mongod --smallfiles --bind_ip_all
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./script/start
    volumes:
      - .:/workspace
      - bundler:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
  webpacker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./script/webpacker
    volumes:
      - .:/workspace
      - bundler:/usr/local/bundle
    ports:
      - "3035:3035"
volumes:
  bundler: {}
