db:
  image: mongo
  command: mongod --smallfiles
  ports:
    - "27017"
    - "28017"
web:
  build: .
  dockerfile: Dockerfile.dev
  command: ./script/start
  volumes:
    - .:/workspace
  volumes_from:
    - bundler
  ports:
    - "3000:3000"
  links:
    - db
bundler:
  image: busybox
  volumes:
    - /bundler
