db:
  image: dockerfile/mongodb
  ports:
    - "27017"
    - "28017"
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/workspace
  ports:
    - "3000:3000"
  links:
    - db
